### ISSUE TITLE
the git page 404 error

### ISSUE THREAD

**Issue by TheMaestro0** [Custom-Tech-Enterprize/website.#16]
the website page is not rendering when you go to the link! link: https://themaestro0.github.io/Custom-Tech-Enterprize/

Note: I think I fixed it! Can you please review it?

**Comment by TheMaestro0** [comment]
I fixed it!

**Comment by TheMaestro0** [comment]
I think we fixed it!

**Comment by Soezdemir23** [comment]
Are you sure that this is the intended repo we are supposed to work on?
This project refers to your Fork and I still see a 404 gitpage error.

**Comment by Soezdemir23** [comment]
Ok, so this was the wrong link, needed to make sure, since I got the feeling we are working on two different forks/repos.
Looks good to me now
